#!/bin/sh
# Polyseat - cap the framerate in a seat to the one the client asked for.
#
#   polyseat-fps          take the framerate from Sunshine's environment
#   polyseat-fps off      take the cap off again
#
# The seat's output already runs at the client's refresh rate, and that paces
# anything that waits for vblank. It is not enough. A game with vsync off
# renders as fast as the card allows, and everything above the client's rate is
# heat and a longer queue rather than a frame anybody sees. Turning vsync on to
# stop that is the wrong trade: it costs latency, which is the one thing a
# stream has least of to spare.
#
# So the games stay uncapped in their own settings and the limit is applied from
# outside, to everything at once. This is what RTSS does on Windows; on Linux
# the equivalent is MangoHud, which limits through a Vulkan layer and, for
# OpenGL, through a preloaded shim. Both read this file, so one file caps a
# native game, a game under Proton, a flatpak launcher and an emulator without
# any of them being configured.
#
# Read at application start, so the cap reaches whatever is started while a
# client is connected. Games already running when a client arrives keep the
# framerate they started with.
#
# Never fails: this runs as a Sunshine prep command, and a prep command that
# returns non-zero stops the stream from starting at all. A seat rendering more
# frames than it transmits still plays.

: "${XDG_CONFIG_HOME:=$HOME/.config}"

DIR=$XDG_CONFIG_HOME/MangoHud
CONF=$DIR/MangoHud.conf

say() { echo "polyseat-fps: $*" >&2; }

write() {
    mkdir -p "$DIR" 2>/dev/null || {
        say "cannot write $DIR, leaving the framerate alone"
        exit 0
    }

    # Written whole and moved into place, because a game starting at the same
    # moment would otherwise read half a file.
    {
        echo "# Generated by polyseat-fps. Edits are overwritten on the next"
        echo "# connection."
        echo ""

        # No overlay. The point here is the limiter, and an FPS counter burned
        # into somebody's stream is a surprise rather than a feature.
        echo "no_display=1"

        # An "if" rather than a test and an echo joined by "and": with no cap to
        # write, the joined form is a false last command, the whole block
        # reports failure, and taking the cap off reported that it could not
        # write a file it had just written perfectly well.
        if [ -n "$1" ]; then
            echo "fps_limit=$1"

            # How the limiter waits, and it is not a detail. MangoHud's default
            # is "late": render the frame the moment the last one was presented,
            # then sleep out the rest of the interval. The frame is therefore
            # almost a whole interval old by the time it is shown, and on a
            # stream that age is added to every other delay in the chain.
            # "early" sleeps first and renders last, so what goes out is as
            # fresh as the cap allows. Same framerate, same heat, less lag.
            echo "fps_limit_method=early"

            # And how the finished frame reaches the compositor. A game with a
            # FIFO swapchain queues frames and waits for them to drain, which is
            # a queue nobody sees the far end of over a stream. Mailbox keeps
            # only the newest, so the frame sway hands to Sunshine is the last
            # one the game drew rather than the oldest one still in line.
            #
            # Deliberately written only alongside a cap. Mailbox never blocks
            # the game, so it is the cap that keeps a seat from rendering flat
            # out; without one, a game left running after the stream ended would
            # go back to the thousands of frames a second this file exists to
            # prevent.
            echo "vulkan_present_mode=mailbox"
        fi
    } > "$CONF.tmp" 2>/dev/null || {
        say "cannot write $CONF, leaving the framerate alone"
        exit 0
    }

    mv "$CONF.tmp" "$CONF" 2>/dev/null || {
        rm -f "$CONF.tmp" 2>/dev/null
        say "cannot replace $CONF, leaving the framerate alone"
        exit 0
    }
}

case "$1" in
    off)
        write ""
        say "cap removed"
        ;;
    *)
        fps=$SUNSHINE_CLIENT_FPS

        # Sunshine has been seen to leave the framerate out, and a made up
        # number would be worse than no cap: too low and the stream stutters
        # for no reason anybody can see from the client.
        case "$fps" in
            '' | *[!0-9]* | 0)
                say "Sunshine reported no framerate, leaving the cap off"
                write ""
                exit 0
                ;;
        esac

        write "$fps"
        say "capped at $fps fps"
        ;;
esac

exit 0
